services:
  - type: web
    name: job-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: GITHUB_REPO
        value: yzuxqz/Job
      - key: GITHUB_BRANCH
        value: main
      - key: GITHUB_TOKEN
        sync: false
